# Generated by Django 3.2.23 on 2024-01-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
    ]
